//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSWEBTA01.Modelos.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class postulante
    {
        public int postulanteId { get; set; }
        public string nombreCompleto { get; set; }
        public string dni { get; set; }
        public string telefono { get; set; }
        public System.DateTime fechaPostulacion { get; set; }
        public int especialidadId { get; set; }
    
        public virtual especialidad especialidad1 { get; set; }
    }
}
